version: "3.2"

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  home-dir:

services:
  &app-service app: &app-service-template
    image: registry.gitlab.com/pymba86/fias-es/app:${CI_COMMIT_SHA}
    hostname: *app-service
    environment:
      FPM_PORT: &php-fpm-port 9000
      FPM_USER: "${USER_ID:-1000}"
      FPM_GROUP: "${GROUP_ID:-1000}"
      APP_ENV: local
      APP_DEBUG: 'true'
      HOME: /home/user
    command: keep-alive.sh
    networks:
      - backend-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./src:/app:rw
      - home-dir:/home/user

  &php-fpm-service php-fpm:
    <<: *app-service-template
    user: 'root:root'
    restart: always
    hostname: *php-fpm-service
    ports: [*php-fpm-port]
    entrypoint: /fpm-entrypoint.sh
    command: php-fpm --nodaemonize -d "opcache.enable=0" -d "display_startup_errors=On" -d "display_errors=On" -d "error_reporting=E_ALL"
    networks:
      - backend-network
      - frontend-network

  nginx:
    image: registry.gitlab.com/pymba86/fias-es/nginx:${CI_COMMIT_SHA}
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    working_dir: /usr/share/nginx/html
    environment:
      FPM_HOST: *php-fpm-service
      FPM_PORT: *php-fpm-port
      ROOT_DIR: '/app/public' # Путь к приложению должен равняться пути к контейнеру php-fpm
    volumes:
      - ./src:/app:ro
    ports: ['80:80']
    depends_on:
      - *php-fpm-service
    networks:
      - frontend-network